using System.Collections.Generic;

namespace KinetixFlowEngine.Core.Gpt.Models
{
    public sealed class GptAssessment
    {
        public string DirectionalBias { get; init; } = string.Empty;

        public string RecommendedAction { get; init; } = string.Empty;

        public int LongConfidence { get; init; }

        public int ShortConfidence { get; init; }

        // Changed from decimal to int to perfectly map to your normalization clamp loop
        public double Score { get; init; }

        public double TrendQuality { get; set; }

        public double FlowQuality { get; set; }

        public double RegimeQuality { get; set; }

        public string RiskLevel { get; init; } = string.Empty;

        public string StateAssessment { get; init; } = string.Empty;

        public string Summary { get; init; } = string.Empty;

        public string Tradeability { get; init; } = string.Empty;

        public List<string> KeyDrivers { get; init; } = [];

        public List<string> Contradictions { get; init; } = [];

        public string DominantIntent { get; init; } = string.Empty;

        // FIXED: Changed from List<string> to an array/list of the complex evidence object
        public List<BehaviorEvidenceItem> BehaviorEvidence { get; init; } = [];

        public string MarketStructure { get; init; } = string.Empty;
    }

    /// <summary>
    /// Captures the structured key-value-interpretation objects generated by the local LLM.
    /// </summary>
    public sealed class BehaviorEvidenceItem
    {
        public string Metric { get; init; } = string.Empty;

        // Using JsonElement or object allows the reader to cleanly map both strings or floating points seamlessly
        public object Value { get; init; } = string.Empty;

        public string Interpretation { get; init; } = string.Empty;
    }

    public enum RiskLevel
    {
        Low,
        Medium,
        High
    }

    public enum DirectionalBias
    {
        Neutral = 0,
        Long = 1,
        Short = 2
    }

    public enum StateAssessment
    {
        Accelerating = 0,
        Strengthening = 1,
        Ranging = 2,
        Exhausting = 3,
        Reversing = 4
    }
}