// <auto-generated />
using System;
using KinetixFlowEngine.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KinetixFlowEngine.Core.Migrations
{
    [DbContext(typeof(KinetixDbContext))]
    [Migration("20260620144527_AddGptTables")]
    partial class AddGptTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KinetixFlowEngine.Core.Database.MarketOutcomeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ATRAtReview")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction15m")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direction30m")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direction60m")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Move15m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Move30m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Move60m")
                        .HasColumnType("numeric");

                    b.Property<double>("MoveATR15m")
                        .HasColumnType("double precision");

                    b.Property<double>("MoveATR30m")
                        .HasColumnType("double precision");

                    b.Property<double>("MoveATR60m")
                        .HasColumnType("double precision");

                    b.Property<double>("MovePct15m")
                        .HasColumnType("double precision");

                    b.Property<double>("MovePct30m")
                        .HasColumnType("double precision");

                    b.Property<double>("MovePct60m")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price15m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price30m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price60m")
                        .HasColumnType("numeric");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("MarketOutcomes");
                });

            modelBuilder.Entity("KinetixFlowEngine.Core.Database.MarketSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ATR15m")
                        .HasColumnType("double precision");

                    b.Property<double>("Acceleration10m")
                        .HasColumnType("double precision");

                    b.Property<double>("Acceleration30m")
                        .HasColumnType("double precision");

                    b.Property<double>("Acceleration60m")
                        .HasColumnType("double precision");

                    b.Property<double>("AskWallAge10m")
                        .HasColumnType("double precision");

                    b.Property<double>("AskWallAge30m")
                        .HasColumnType("double precision");

                    b.Property<double>("AskWallAge60m")
                        .HasColumnType("double precision");

                    b.Property<double>("AskWallQty10m")
                        .HasColumnType("double precision");

                    b.Property<double>("AskWallQty30m")
                        .HasColumnType("double precision");

                    b.Property<double>("AskWallQty60m")
                        .HasColumnType("double precision");

                    b.Property<double>("BidWallAge10m")
                        .HasColumnType("double precision");

                    b.Property<double>("BidWallAge30m")
                        .HasColumnType("double precision");

                    b.Property<double>("BidWallAge60m")
                        .HasColumnType("double precision");

                    b.Property<double>("BidWallQty10m")
                        .HasColumnType("double precision");

                    b.Property<double>("BidWallQty30m")
                        .HasColumnType("double precision");

                    b.Property<double>("BidWallQty60m")
                        .HasColumnType("double precision");

                    b.Property<double>("CompressionZ10m")
                        .HasColumnType("double precision");

                    b.Property<double>("CompressionZ30m")
                        .HasColumnType("double precision");

                    b.Property<double>("CompressionZ60m")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DepthBullPct10m")
                        .HasColumnType("double precision");

                    b.Property<double>("DepthBullPct30m")
                        .HasColumnType("double precision");

                    b.Property<double>("DepthBullPct60m")
                        .HasColumnType("double precision");

                    b.Property<double>("DepthImbalance10m")
                        .HasColumnType("double precision");

                    b.Property<double>("DepthImbalance30m")
                        .HasColumnType("double precision");

                    b.Property<double>("DepthImbalance60m")
                        .HasColumnType("double precision");

                    b.Property<double>("ER30_10m")
                        .HasColumnType("double precision");

                    b.Property<double>("ER30_30m")
                        .HasColumnType("double precision");

                    b.Property<double>("ER30_60m")
                        .HasColumnType("double precision");

                    b.Property<double>("ER5_10m")
                        .HasColumnType("double precision");

                    b.Property<double>("ER5_30m")
                        .HasColumnType("double precision");

                    b.Property<double>("ER5_60m")
                        .HasColumnType("double precision");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ExhaustionZ10m")
                        .HasColumnType("double precision");

                    b.Property<double>("ExhaustionZ30m")
                        .HasColumnType("double precision");

                    b.Property<double>("ExhaustionZ60m")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowImpact10m")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowImpact30m")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowImpact60m")
                        .HasColumnType("double precision");

                    b.Property<double>("FundingPressure")
                        .HasColumnType("double precision");

                    b.Property<double>("FundingRate")
                        .HasColumnType("double precision");

                    b.Property<double>("ImbalanceZ10m")
                        .HasColumnType("double precision");

                    b.Property<double>("ImbalanceZ30m")
                        .HasColumnType("double precision");

                    b.Property<double>("ImbalanceZ60m")
                        .HasColumnType("double precision");

                    b.Property<double>("Momentum10m")
                        .HasColumnType("double precision");

                    b.Property<double>("Momentum30m")
                        .HasColumnType("double precision");

                    b.Property<double>("Momentum60m")
                        .HasColumnType("double precision");

                    b.Property<double>("NetPressure10m")
                        .HasColumnType("double precision");

                    b.Property<double>("NetPressure30m")
                        .HasColumnType("double precision");

                    b.Property<double>("NetPressure60m")
                        .HasColumnType("double precision");

                    b.Property<double>("OIChange")
                        .HasColumnType("double precision");

                    b.Property<double>("Persistence10m")
                        .HasColumnType("double precision");

                    b.Property<double>("Persistence30m")
                        .HasColumnType("double precision");

                    b.Property<double>("Persistence60m")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<double>("ScoreZ10m")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreZ30m")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreZ60m")
                        .HasColumnType("double precision");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VWAP")
                        .HasColumnType("numeric");

                    b.Property<double>("VelocityZ10m")
                        .HasColumnType("double precision");

                    b.Property<double>("VelocityZ30m")
                        .HasColumnType("double precision");

                    b.Property<double>("VelocityZ60m")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("KinetixFlowEngine.Core.Database.ModelReviewEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BehaviorEvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContradictionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Correct15m")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Correct30m")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Correct60m")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DirectionalBias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DominantIntent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlowQuality")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FutureMove15m")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureMove30m")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FutureMove60m")
                        .HasColumnType("numeric");

                    b.Property<string>("KeyDriversJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LongConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("MarketStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegimeQuality")
                        .HasColumnType("integer");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("ShortConfidence")
                        .HasColumnType("integer");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrendQuality")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("ModelReviews");
                });

            modelBuilder.Entity("KinetixFlowEngine.Core.Database.MarketOutcomeEntity", b =>
                {
                    b.HasOne("KinetixFlowEngine.Core.Database.MarketSnapshotEntity", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("KinetixFlowEngine.Core.Database.ModelReviewEntity", b =>
                {
                    b.HasOne("KinetixFlowEngine.Core.Database.MarketSnapshotEntity", "Snapshot")
                        .WithMany("Reviews")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("KinetixFlowEngine.Core.Database.MarketSnapshotEntity", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
