// <auto-generated />
using System;
using KinetixFlowEngine.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KinetixFlowEngine.Core.Migrations
{
    [DbContext(typeof(KinetixDbContext))]
    partial class KinetixDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KinetixFlowEngine.Core.Database.Entities.MarketStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("EngineBuild")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<byte>("QualityScore")
                        .HasColumnType("smallint");

                    b.Property<short>("Regime")
                        .HasColumnType("smallint");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<short>("Timeframe")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sequence");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("Timeframe", "TimestampUtc");

                    b.ToTable("market_state", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
